env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  indent:
    - warn
    - 4
  linebreak-style:
    - error
    - windows
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
  space-before-blocks:
    - warn
    - always
  keyword-spacing:
    - warn
  object-curly-spacing: 
    - warn
    - always
  space-infix-ops:
    - warn
  semi-spacing:
    - warn
  key-spacing:
    - warn
  comma-spacing:
    - warn
  block-spacing:
    - warn
    - always
  arrow-spacing:
   - warn
  padding-line-between-statements:
    - warn
    - blankLine: always
      prev: "*"
      next: function
    - blankLine: always
      prev: "*"
      next: for
    - blankLine: always
      prev: "*"
      next: if
    - blankLine: always
      prev: "*"
      next: do
    - blankLine: always
      prev: "*"
      next: class
    - blankLine: always
      prev: "*"
      next: export
    - blankLine: always
      prev: "*"
      next: return
  no-trailing-spaces: 
    - warn
    - skipBlankLines: true
